export const SET_DATA = 'SET_DATA'
export const SELECT_DATA = 'SELECT_DATA'
export const DELETE_DATA = 'DELETE_DATA'
export const ADD_CART = 'ADD_CART'
export const ADD_WISHLIST ='ADD_WISHLIST'
export const REMOVE_DATA = 'REMOVE_DATA'